openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Vehicle Store API"
  description: "API documentation for the Vehicle Store"

servers:
  - url: "http://localhost:3001/api/v1"

paths:
  /vehicle:
    post:
      summary: "Adds a new vehicle to the system"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Vehicle"
      responses:
        '201':
          description: "Vehicle successfully added"
        '400':
          description: "Bad Request"
    get:
      summary: "Finds all vehicles, it is possible to filter by status"
      parameters:
        - in: query
          name: sold
          schema:
            type: string
          required: false
          description: The status of the vehicles to retrieve
      responses:
        '200':
          description: "Successful operation"
        '404':
          description: "Vehicle not found"

  /vehicle/{vehicleId}:
    put:
      summary: "Updates the details of a specific vehicle"
      parameters:
        - in: path
          name: vehicleId
          schema:
            type: string
          required: true
          description: The id of the vehicle to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Vehicle"
      responses:
        '200':
          description: "Vehicle successfully updated"
        '404':
          description: "Vehicle not found"
        '400':
          description: "Bad Request"
    get:
      summary: "Fetches the details of a specific vehicle"
      parameters:
        - in: path
          name: vehicleId
          schema:
            type: string
          required: true
          description: The id of the vehicle to retrieve
      responses:
        '200':
          description: "Successful operation"
        '404':
          description: "Vehicle not found"
    delete:
      summary: "Removes a specific vehicle from the system"
      parameters:
        - in: path
          name: vehicleId
          schema:
            type: string
          required: true
          description: The id of the vehicle to delete
      responses:
        '204':
          description: "Vehicle successfully deleted"
        '404':
          description: "Vehicle not found"

  /store/order:
    post:
      summary: "Places an order for a vehicle"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        '201':
          description: "Order successfully placed"
        '400':
          description: "Bad Request"

  /store/order/{orderId}:
    get:
      summary: "Fetches details of a specific order"
      parameters:
        - in: path
          name: orderId
          schema:
            type: string
          required: true
          description: The id of the order to retrieve
      responses:
        '200':
          description: "Successful operation"
        '404':
          description: "Order not found"

  /user/{googleId}:
    get:
      summary: "Fetches the profile of a specific user"
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The username of the user to retrieve
      responses:
        '200':
          description: "Successful operation"
        '404':
          description: "User not found"
    put:
      summary: "Updates the profile of a specific user"
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The username of the user to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: "User successfully updated"
        '404':
          description: "User not found"
        '400':
          description: "Bad Request"
    delete:
      summary: "Deletes a specific user"
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The username of the user to delete
      responses:
        '204':
          description: "User successfully deleted"
        '404':
          description: "User not found"

components:
  schemas:
    Vehicle:
      type: object
      required:
        - name
        - make
        - year
        - color
        - stock
        - price
        - sold
        - description
        - category
        - buyer
      properties:
        name:
          type: string
          description: The name of the vehicle
        make:
          type: string
          description: The make of the vehicle
        year:
          type: integer
          format: int32
          description: The manufacturing year of the vehicle
        color:
          type: string
          description: The color of the vehicle
        stock:
          type: integer
          format: int32
          description: The stock amount of the vehicle
        price:
          type: number
          format: double
          description: The price of the vehicle
        sold:
          type: boolean
          description: The status of the sold
        description:
          type: string
          description: The description of the vehicle
        category:
          type: string
          description: The category of the vehicle
        buyer:
          type: string
          description: The buyer of the vehicle
    Order:
      type: object
      required:
        - vehicleId
        - userId
        - sellPrice
        - taxRate
        - totalAmount
        - createdAt
      properties:
        vehicleId:
          type: string
          description: The id of the vehicle
        userId:
          type: string
          description: The id of the user
        sellPrice:
          type: number
          format: double
          description: The sell price of the vehicle
        taxRate:
          type: number
          format: double
          description: The tax rate in decimal
        totalAmount:
          type: number
          format: double
          description: The total of the order (sellPrice + taxRate)
        createdAt:
          type: string
          format: date
          readOnly: true
          description: The datetime of the order creation
    User:
      type: object
      # Define the User schema here
